### ISSUE TITLE
electron.js: Cannot read property 'format' of undefined - var url = process.env.E_URL || url.format(

### ISSUE THREAD

**Issue by Mechatronix** [lohanitech/ion-electron#2]
Hi, 

first of all thanks for your example. Everything is working fine but if i Run the packaged version, I'm running into the Exception "Cannot read property 'format' of undefined electron.js Line 20". 

What's the diffrent, so it is working for you. 

Thanks for your help 

Sebi

**Comment by lohanidamodar** [comment]
I am not sure without the further details, if it's working in development version it must work on the packaged version. 
try by changing the line
```
var url = process.env.E_URL || url.format( ...
```
to
```
var url = process.env.E_URL || require('url').format( ...
```
 If you continue having problems, you can follow this [tutorial](https://competenepal.com/ionic2-electron/)  to create your own Ionic-Electron starter with all the latest versions as I have not been able to update...And let us know if the problem continues.
