### ISSUE TITLE
npm install error by inotify

### ISSUE THREAD

**Issue by comseong** [lohanitech/ion-electron#3]
Hello, I have met a issue like below during npm install. The inotify requires Linux but my platform is MacOS. I'm not sure that it's normal situation?

npm ERR! notsup Unsupported platform for inotify@1.4.2: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/comseong/dev/electron/ion-electron/npm-debug.log

In the npm-debug.log:

2178 verbose stack Error: Unsupported platform for inotify@1.4.2: wanted {"name":"inotify","version":"1.4.2","author":{"name":"Camilo Aguilar","email":"camilo.aguilar@gmail.com"},"email":"camilo.aguilar@gmail.com","keywords":["inotify","watch","monitor","watch files","watch directories"],"license":"MIT","description":"inotify bindings for v8 javascript engine","repository":{"type":"git","url":"git+ssh://git@github.com/c4milo/node-inotify.git"},"os":["linux"],"engines":{"node":">=0.8"},"main":"inotify","dependencies":{"bindings":"^1.2.1","nan":"^2.3.3"},"scripts":{"test":"node-gyp configure build","install":"node-gyp rebuild"},"gypfile":true,"contributors":[{"name":"Adrian Estrada","email":"edsadr@gmail.com"},{"name":"Alexander Makarenko","email":"estliberitas@gmail.com"},{"name":"Brian Ingalls","email":"bingalls@compete.com"},{"name":"Brian White","email":"mscdex@mscdex.net"},{"name":"Camilo Aguilar","email":"camilo.aguilar@gmail.com"},{"name":"Dan VerWeire","email":"dverweire@gmail.com"},{"name":"FrozenCow","email":"frozencow@gmail.com"},{"name":"Michael Boe","email":"mschuylerb@gmail.com"},{"name":"Yannick Croissant","email":"k1der.country@free.fr"},{"name":"ikokostya","email":"ikokostya@gmail.com"}],"gitHead":"5feed6dc40be4a5d76ae9d30cf339e4f7d70ae54","bugs":{"url":"https://github.com/c4milo/node-inotify/issues"},"homepage":"https://github.com/c4milo/node-inotify#readme","_id":"inotify@1.4.2","_npmVersion":"5.3.0","_nodeVersion":"8.3.0","_npmUser":{"name":"c4milo","email":"camilo.aguilar@gmail.com"},"maintainers":[{"name":"camilo","email":"camilo@cloudescape.com"},{"name":"c4milo","email":"camilo.aguilar@gmail.com"}],"dist":{"integrity":"sha512-+dq8cO+Um/EiGujOilVGw1AclDq9V4B23z4I+PpytUlgIrWfOG/KxW4k7pRZwHHSoqUzlScCWYuQS8Wa+hYcXg==","shasum":"fd69d0f6e4a55005e338b3c1852fbb81acfb3ccc","tarball":"https://registry.npmjs.org/inotify/-/inotify-1.4.2.tgz"},"_npmOperationalInternal":{"host":"s3://npm-registry-packages","tmp":"tmp/inotify-1.4.2.tgz_1505073926403_0.6098344896454364"},"directories":{},"_from":"inotify@>= 0.1.6","_resolved":"https://registry.npmjs.org/inotify/-/inotify-1.4.2.tgz","_shasum":"fd69d0f6e4a55005e338b3c1852fbb81acfb3ccc","_requested":{"raw":"inotify@>= 0.1.6","scope":null,"escapedName":"inotify","name":"inotify","rawSpec":">= 0.1.6","spec":">=0.1.6","type":"range"},"_spec":"inotify@>= 0.1.6","_where":"/Users/comseong/dev/electron/ion-electron/node_modules/dev","_args":[[{"raw":"inotify@>= 0.1.6","scope":null,"escapedName":"inotify","name":"inotify","rawSpec":">= 0.1.6","spec":">=0.1.6","type":"range"},"/Users/comseong/dev/electron/ion-electron/node_modules/dev"]],"readme":"ERROR: No README data found!"} (current: {"os":"darwin","cpu":"x64"})
2178 verbose stack     at checkPlatform (/usr/local/lib/node_modules/npm/node_modules/npm-install-checks/index.js:45:14)
2178 verbose stack     at thenWarnEngineIssues (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:41:5)
2178 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
2178 verbose stack     at checkEngine (/usr/local/lib/node_modules/npm/node_modules/npm-install-checks/index.js:24:10)
2178 verbose stack     at module.exports.isInstallable (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:38:3)
2178 verbose stack     at resolveWithNewModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:511:10)
2178 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:454:9
2178 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
2178 verbose stack     at /usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
2178 verbose stack     at addRequestedAndFinish (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:67:5)

**Comment by lohanidamodar** [comment]
This might be NPM error, try using [yarn](https://yarnpkg.com/en/)

**Comment by comseong** [comment]
I think this issue is now meaningless because you changed this git repository. I'll open new one.
