### ISSUE TITLE
I got stuck in this part2 with the latest Ionic and Electron.

### ISSUE THREAD

**Issue by comseong** [lohanitech/ion-electron#4]
Very thank for your tutorial. I’ve passed tutorial part 1 with the latest Ionic and Electron but faced a problem in this part2 with the latest Ionic and Electron.

My environment is like below.

Ionic Framework: 3.8.0 
Ionic App Scripts: 3.0.1 
Angular Core: 4.4.4 
Angular Compiler CLI: 4.4.4 
Node: 6.11.4 
OS Platform: macOS Sierra
Electron: 1.7.9

By this code in the provider,
zoomIn(){
electron.webFrame.setZoomLevel(++this.currentZoom);
}

Ionic spit out the error at fs.existsSync function call in node_modules/electron/index.js.

Runtime Error
fs.existsSync is not a function
Stack
TypeError: fs.existsSync is not a function at Object.<anonymous> (http://localhost:8100/build/vendor.js:115286:8) at Object.splitPathRe (http://localhost:8100/build/vendor.js:115292:30) at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30) at Object.262 (http://localhost:8100/build/main.js:204:67) at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30) at Object.192 (http://localhost:8100/build/main.js:42:89) at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30) at Object.261 (http://localhost:8100/build/main.js:161:75) at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30) at Object.212 (http://localhost:8100/build/main.js:100:73)

![image](https://user-images.githubusercontent.com/3951319/32363172-bfa903d2-c08f-11e7-9bc9-4e7af4f81b52.png)

How can I solve this issue? Thanks in advance.

**Comment by comseong** [comment]
I've changed Ionic(3.8.0) and Electron(1.7.9) to the older(3.7.0 and 1.7.5) like this repository and tried again. But still it has same issue.

**Comment by lohanidamodar** [comment]
Hi, it is all because of the changes made tolatest ionic, So I have updated the repository and also the tutorial. Please check [Competenepal](https://competenepal.com/ionic2-electron/)

**Comment by comseong** [comment]
Thank you for your all update with the latest Ionic. As your recommendation, I followed up the new updated tutorial at your blog. But as a result, I have met the same issue #5 again.

**Comment by lohanidamodar** [comment]
hi,
After adding electron specific library, you will not be able to view the app in browser, you must view it in electron shell. check #5
