### ISSUE TITLE
Runtime Error: require is not defined

### ISSUE THREAD

**Issue by comseong** [lohanitech/ion-electron#5]
I did git clone with this repository and then did npm install & npm run dev, I've met this issue now.

![image](https://user-images.githubusercontent.com/3951319/32364417-94f92dea-c096-11e7-9c3d-aee4833521a7.png)

**Comment by comseong** [comment]
I found additional log at console. I attached this.

![image](https://user-images.githubusercontent.com/3951319/32364613-a06001a8-c097-11e7-9618-c1eb6559546b.png)

**Comment by lohanidamodar** [comment]
Hi,
After adding electron specifit library as we did in the provider, part 2 of the tutorial, you cannot view the app in the browser, you must view it in the electron shell. It will not work on browser, but work with electron. `npm run dev` should launch electron too, where you should see it working, if it shows blank, just reload electron shell after you see ionic serve finish at your terminal
