### ISSUE TITLE
[DONE] Killing all processes with signal  null

### ISSUE THREAD

**Issue by comseong** [lohanitech/ion-electron#8]
Hello, thank you for great tutorial but it doesn't work at both Windows 7 and Windows 10.
When I tried like below:

git clone https://github.com/lohanitech/ion-electron.git
npm install
npm run dev

Result:

> nf start

[WARN] No ENV file found
01:05:55 ionic.1      |  'yarn'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
01:05:55 ionic.1      |  ��ġ ������ �ƴմϴ�.
[DONE] Killing all processes with signal  null
01:05:55 ionic.1      Exited with exit code 1
01:06:16 electron.1   |  (node:1080) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by comseong** [comment]
You have to install yarn by npm install -g yarn

**Comment by lohanidamodar** [comment]
Or, you could just change yarn to npm in Procfile
